<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Interfaces.Business</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain.Interfaces\Domain.Interfaces.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Serilog" Version="4.2.0" />
    </ItemGroup>

</Project>
